//addsnipergear.sqf
//By GySgt J.Long
this = player;
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
sleep 2;
this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 3 do {this addItemToUniform "rhsusf_5Rnd_300winmag_xm2010";};
this addVest "rhsusf_spc_marksman";
for "_i" from 1 to 4 do {this addItemToVest "rhsusf_5Rnd_300winmag_xm2010";};
for "_i" from 1 to 4 do {this addItemToVest "rhsusf_mag_15Rnd_9x19_JHP";};
this addBackpack "rhsusf_assault_eagleaiii_coy";
this addHeadgear "rhsusf_lwh_helmet_marpatwd";
this addGoggles "rhs_googles_clear";
this addWeapon "rhs_weap_XM2010";
this addPrimaryWeaponItem "ACE_optic_SOS_PIP";
this addPrimaryWeaponItem "rhsusf_acc_harris_bipod";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ACE_Altimeter";
this linkItem "tf_anprc152_3";
this linkItem "ItemGPS";
this linkItem "NVGoggles_OPFOR";
